apiVersion: apps/v1
kind: Deployment
metadata:
  name: apps-testing-argo
spec:
  replicas: 3
  selector:
    matchLabels:
      apps-type: apps-testing-argo
  template:
    metadata:
      labels:
        apps-type: apps-testing-argo
    spec:
      containers:
      - name: ct-nginx
        image: nginx
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: svc-testing-argo
spec:
  type: NodePort
  selector:
    apps-type: apps-testing-argo
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30005
